<a href="https://colab.research.google.com/github/manojmulammagari/data-analysis-python-practice/blob/main/Pandas_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd

In [15]:
df=pd.read_excel('df.xlsx')
df

,bedroom,bathrooms,area,furnishing,avalable_for,address,floor_number,facing,floor_type,gate_community,...,pooja_room,study_room,others,servant_room,store_room,maintenance_amt,brok_amt,deposit_amt,mnt_amt,rent
0,NaN,2.0,0.0,Semifurnished,All,"Bella Casa Baner, Baner, , Pune, Maharashtra",1,No Direction,Not provided,No,...,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,18500.0
1,2.0,2.0,1050.0,Semifurnished,All,"Paranjape Blue Ridge, Hinjewadi, , Pune, Mahar...",2,West,Not provided,Yes,...,0,0,0.0,0.0,0.0,0,0.0,63000.0,0.0,21000.0
2,2.0,NaN,900.0,Semifurnished,All,"Simplicity Apartments, Handewadi, , Pune, Maha...",6,No Direction,Not provided,Yes,...,0,0,0.0,0.0,0.0,0,0.0,25000.0,0.0,12000.0
3,3.0,3.0,1100.0,Furnished,Family Only,"GK Dwarka Queens Park, Rahatani, , Pune, Mahar...",1,East,Others,Yes,...,0,0,0.0,0.0,0.0,0,24000.0,3.0,0.0,24000.0
4,1.0,1.0,605.0,Semifurnished,Family Only,"Anandtara Sayajiraje Avenue, Sasane Colony, , ...",4,East,Vitrified,Yes,...,0,0,1.0,0.0,0.0,0,0.0,3.0,0.0,13500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5356,2.0,2.0,0.0,Unfurnished,All,"Kesar Imperial Blue, Dighi, , Pune, Maharashtra",2,East,Marble,Yes,...,0,0,0.0,0.0,0.0,0,0.0,30000.0,0.0,14000.0
5357,1.0,1.0,0.0,Unfurnished,Bachelors (Men Only),"Karve Nagar, , Pune, Maharashtra",0,No Direction,Not provided,No,...,0,0,0.0,0.0,0.0,0,0.0,20000.0,0.0,10000.0
5358,3.0,3.0,1300.0,Semifurnished,All,"Kolte Patil IVY Estate, Wagholi, , Pune, Mahar...",5,North-West,Marble,Yes,...,0,0,0.0,0.0,1.0,0,16700.0,45000.0,0.0,16700.0
5359,3.0,3.0,1450.0,Unfurnished,All,"Pride Aloma County, Aundh, , Pune, Maharashtra",9,South-East,Vitrified,Yes,...,0,0,1.0,0.0,0.0,Maintenance 1/ (/ month,1.0,100000.0,1.0,33000.0
5360,2.0,2.0,850.0,Furnished,All,"Swapan Lok Society, Koregaon park, , Pune, Mah...",4,North,Granite,Yes,...,0,0,1.0,0.0,0.0,0,40000.0,120000.0,0.0,40000.0

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5361 entries, 0 to 5360
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   bedroom            5360 non-null   float64
 1   bathrooms          5360 non-null   float64
 2   area               5361 non-null   float64
 3   furnishing         5361 non-null   object
 4   avalable_for       5343 non-null   object
 5   address            5361 non-null   object
 6   floor_number       5361 non-null   int64
 7   facing             5361 non-null   object
 8   floor_type         5361 non-null   object
 9   gate_community     5361 non-null   object
 10  corner_pro         5360 non-null   object
 11  parking            5360 non-null   float64
 12  wheelchairadption  962 non-null    object
 13  petfacility        1201 non-null   object
 14  aggDur             5358 non-null   float64
 15  noticeDur          5361 non-null   int64
 16  lightbill          5357 non-null   float64
 17  powerbackup        5361 non-null   int64
 18  propertyage        5361 non-null   object
 19  no_room            5359 non-null   float64
 20  pooja_room         5361 non-null   int64
 21  study_room         5361 non-null   int64
 22  others             5360 non-null   float64
 23  servant_room       5360 non-null   float64
 24  store_room         5359 non-null   float64
 25  maintenance_amt    5360 non-null   object
 26  brok_amt           5360 non-null   float64
 27  deposit_amt        5359 non-null   float64
 28  mnt_amt            5361 non-null   float64
 29  rent               5361 non-null   float64
dtypes: float64(14), int64(5), object(11)
memory usage: 1.2+ MB

In [17]:
df.columns=df.columns.str.replace("_"," ").str.strip().str.title()
df.columns

Index(['Bedroom', 'Bathrooms', 'Area', 'Furnishing', 'Avalable For', 'Address',
       'Floor Number', 'Facing', 'Floor Type', 'Gate Community', 'Corner Pro',
       'Parking', 'Wheelchairadption', 'Petfacility', 'Aggdur', 'Noticedur',
       'Lightbill', 'Powerbackup', 'Propertyage', 'No Room', 'Pooja Room',
       'Study Room', 'Others', 'Servant Room', 'Store Room', 'Maintenance Amt',
       'Brok Amt', 'Deposit Amt', 'Mnt Amt', 'Rent'],
      dtype='object')

In [18]:
for col in df.select_dtypes(include='object').columns:
  df[col]=df[col].str.strip()

In [19]:
print("Before:",len(df))
df.drop_duplicates()
print("After:",len(df))

Before: 5361
After: 5361

In [20]:
df.isnull().sum()

Bedroom                 1
Bathrooms               1
Area                    0
Furnishing              0
Avalable For           18
Address                 0
Floor Number            0
Facing                  0
Floor Type              0
Gate Community          0
Corner Pro              1
Parking                 1
Wheelchairadption    4399
Petfacility          4160
Aggdur                  3
Noticedur               0
Lightbill               4
Powerbackup             0
Propertyage             0
No Room                 2
Pooja Room              0
Study Room              0
Others                  1
Servant Room            1
Store Room              2
Maintenance Amt      4451
Brok Amt                1
Deposit Amt             2
Mnt Amt                 0
Rent                    0
dtype: int64

In [21]:
df.dropna()

,Bedroom,Bathrooms,Area,Furnishing,Avalable For,Address,Floor Number,Facing,Floor Type,Gate Community,...,Pooja Room,Study Room,Others,Servant Room,Store Room,Maintenance Amt,Brok Amt,Deposit Amt,Mnt Amt,Rent
41,3.0,3.0,1350.0,Unfurnished,All,"Bramha Avenue, NIBM, , Pune, Maharashtra",9,East,Vitrified,Yes,...,0,0,0.0,0.0,1.0,Maintenance 2800/ (/ month,45000.0,3.0,2800.0,27000.0
51,1.0,1.0,0.0,Semifurnished,All,"Rahul Terrace, Rahul Terrace Koregaon Park Lan...",3,North,Marble,Yes,...,0,0,0.0,0.0,0.0,Maintenance 100/ (/ month,20000.0,4.0,100.0,20000.0
71,3.0,3.0,1350.0,Unfurnished,Family Only,"Eisha Bella Vista, NIBM, , Pune, Maharashtra",7,North-East,Vitrified,Yes,...,0,0,0.0,0.0,1.0,Maintenance 1500/ (/ month,20000.0,50000.0,1500.0,20000.0
84,2.0,2.0,1100.0,Semifurnished,All,"Surya Atlantis City, Dhanori, , Pune, Maharashtra",8,East,Vitrified,Yes,...,0,0,1.0,0.0,0.0,Maintenance 100/ ((one time fee,20000.0,60000.0,100.0,20000.0
96,3.0,2.0,1380.0,Semifurnished,Family Only,"Vaishnavi Sai Royale, Wanowrie, , Pune, Mahara...",6,East,Vitrified,Yes,...,0,0,1.0,0.0,0.0,Maintenance 2500/ (/ month,35000.0,90000.0,2500.0,30000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5215,2.0,2.0,800.0,Semifurnished,Family Only,"Kolte Patil Western Avenue, Wakad, , Pune, Mah...",3,East,Vitrified,Yes,...,0,0,1.0,0.0,0.0,Maintenance 2/ (/ unit,19000.0,55000.0,2.0,19000.0
5229,2.0,2.0,724.0,Semifurnished,"Family , Bachelors (Women Only)","Kumar Shantiniketan, Pashan, , Pune, Maharashtra",2,North,Vitrified,Yes,...,0,0,1.0,0.0,0.0,Maintenance 300/ (/ month,18500.0,55000.0,300.0,18500.0
5238,2.0,2.0,1035.0,Semifurnished,All,"Beharay Rathi Anand Residency, Kothrud, , Pune...",5,East,Vitrified,Yes,...,0,0,1.0,0.0,0.0,Maintenance 200/ (/ month,27000.0,3.0,200.0,25000.0
5326,2.0,2.0,0.0,Semifurnished,Family Only,"Suncity Township, Sinhgad Road, , Pune, Mahara...",3,East,Vitrified,Yes,...,0,0,1.0,0.0,0.0,Maintenance 1000/ (/ month,1.0,50000.0,1000.0,17000.0
5343,3.0,3.0,1500.0,Unfurnished,All,"Clover Highlands, Kondhwa, , Pune, Maharashtra",2,East,Vitrified,Yes,...,0,0,0.0,0.0,1.0,Maintenance 1500/ (/ month,37000.0,3.0,1500.0,31500.0

### Sort DataFrame columns
You can sort the columns of a DataFrame alphabetically using `df.sort_index(axis=1)`.

In [22]:
df_sorted_columns = df.sort_index(axis=1)
display(df_sorted_columns.head())

,Address,Aggdur,Area,Avalable For,Bathrooms,Bedroom,Brok Amt,Corner Pro,Deposit Amt,Facing,...,Parking,Petfacility,Pooja Room,Powerbackup,Propertyage,Rent,Servant Room,Store Room,Study Room,Wheelchairadption
0,"Bella Casa Baner, Baner, , Pune, Maharashtra",0.0,0.0,All,2.0,NaN,0.0,No,0.0,No Direction,...,1.0,NaN,0,0,1 to 5 Year Old,18500.0,0.0,0.0,0,NaN
1,"Paranjape Blue Ridge, Hinjewadi, , Pune, Mahar...",24.0,1050.0,All,2.0,2.0,0.0,Yes,63000.0,West,...,1.0,Yes,0,1,0 to 1 Year Old,21000.0,0.0,0.0,0,Yes
2,"Simplicity Apartments, Handewadi, , Pune, Maha...",0.0,900.0,All,NaN,2.0,0.0,No,25000.0,No Direction,...,1.0,NaN,0,2,5 to 10 Year Old,12000.0,0.0,0.0,0,NaN
3,"GK Dwarka Queens Park, Rahatani, , Pune, Mahar...",1.0,1100.0,Family Only,3.0,3.0,24000.0,No,3.0,East,...,1.0,Yes,0,1,5 to 10 Year Old,24000.0,0.0,0.0,0,Yes
4,"Anandtara Sayajiraje Avenue, Sasane Colony, , ...",36.0,605.0,Family Only,1.0,1.0,0.0,Yes,3.0,East,...,1.0,Yes,0,1,5 to 10 Year Old,13500.0,0.0,0.0,0,Yes

### Find columns that contain letters
To find columns that contain letters, we can first filter for `object` type columns (which typically hold strings) and then check each value in those columns for the presence of alphabetic characters using regular expressions.

In [23]:
columns_with_letters = []
for col in df.select_dtypes(include='object').columns:
    # Check if any value in the column contains at least one letter
    if df[col].astype(str).str.contains('[a-zA-Z]').any():
        columns_with_letters.append(col)

print("Columns containing letters:", columns_with_letters)

Columns containing letters: ['Furnishing', 'Avalable For', 'Address', 'Facing', 'Floor Type', 'Gate Community', 'Corner Pro', 'Wheelchairadption', 'Petfacility', 'Propertyage', 'Maintenance Amt']